Repository voxpupuli/puppet-make, pull requests merged in 2021-05, with the labels that each got.

#51 Support Puppet 7
  metadata.json
Labels: enhancement

#57 puppetlabs/stdlib: allow 7.x
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .msync.yml
  Dockerfile
  Gemfile
  REFERENCE.md
  manifests/init.pp
  metadata.json
  spec/acceptance/init_spec.rb
Labels: enhancement

#52 modulesync 4.1.0
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .msync.yml
  Dockerfile
  Gemfile
Labels: modulesync

#58 Add Ubuntu 18.04/20.04 & CentOS 8 support
  metadata.json
Labels: enhancement

#60 Drop EoL Ubuntu 16.04
  metadata.json
Labels: backwards-incompatible

#59 release 4.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
